"""Authoritative Compliance Frameworks & Control Catalogs.

Defines comprehensive, industry-standard controls for SOC 2 Type II, ISO/IEC 27001:2022,
NIST CSF 2.0, PCI-DSS v4.0, HIPAA Security Rule, and GDPR.
"""

from __future__ import annotations

from typing import List, Dict, Any
from cybershield.database.models.compliance import ControlSeverity


FRAMEWORK_DEFINITIONS = [
    {
        "id": "SOC2",
        "name": "SOC 2 Type II",
        "version": "2024",
        "description": "AICPA Trust Services Criteria evaluating Security, Availability, Processing Integrity, Confidentiality, and Privacy over time.",
        "category": "TRUST_SERVICES",
    },
    {
        "id": "ISO27001",
        "name": "ISO/IEC 27001:2022",
        "version": "2022",
        "description": "International standard specifying requirements for establishing, implementing, maintaining, and continually improving an ISMS.",
        "category": "INFORMATION_SECURITY",
    },
    {
        "id": "NIST_CSF",
        "name": "NIST Cybersecurity Framework",
        "version": "2.0",
        "description": "National Institute of Standards and Technology Framework for Improving Critical Infrastructure Cybersecurity (Govern, Identify, Protect, Detect, Respond, Recover).",
        "category": "CRITICAL_INFRASTRUCTURE",
    },
    {
        "id": "PCI_DSS",
        "name": "PCI-DSS",
        "version": "v4.0",
        "description": "Payment Card Industry Data Security Standard technical and operational requirements to protect payment cardholder data.",
        "category": "PAYMENT_SECURITY",
    },
    {
        "id": "HIPAA",
        "name": "HIPAA Security Rule",
        "version": "45 CFR Part 164",
        "description": "Health Insurance Portability and Accountability Act national standards for protecting electronic protected health information (ePHI).",
        "category": "HEALTHCARE_PRIVACY",
    },
    {
        "id": "GDPR",
        "name": "GDPR",
        "version": "Regulation (EU) 2016/679",
        "description": "European Union General Data Protection Regulation governing data protection, privacy, and incident notification mandates.",
        "category": "DATA_PRIVACY",
    },
]


CONTROL_CATALOG: List[Dict[str, Any]] = [
    # --- SOC 2 Type II ---
    {
        "id": "SOC2-CC6.1",
        "framework_id": "SOC2",
        "control_code": "CC6.1",
        "title": "Logical Access and Authentication Controls",
        "domain": "Logical Access",
        "description": "The entity implements logical access security software, infrastructure, and architectures over protected information assets.",
        "remediation_guidance": "Enforce strong password policies, multi-factor authentication, and verify all active accounts have distinct role assignments.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_access_controls",
    },
    {
        "id": "SOC2-CC6.6",
        "framework_id": "SOC2",
        "control_code": "CC6.6",
        "title": "Perimeter Boundary & Network Segmentation",
        "domain": "Logical Access",
        "description": "The entity implements logical boundaries and network segmentation to prevent unauthorized lateral movement.",
        "remediation_guidance": "Verify all network subnets are zoned (DMZ, Internal, Quarantine) and rogue device discovery alerts are addressed.",
        "severity": ControlSeverity.HIGH,
        "evaluator_key": "eval_network_segmentation",
    },
    {
        "id": "SOC2-CC6.8",
        "framework_id": "SOC2",
        "control_code": "CC6.8",
        "title": "Malicious Code Prevention & Detection",
        "domain": "Logical Access",
        "description": "The entity implements controls to prevent or detect and act upon the introduction of unauthorized or malicious software.",
        "remediation_guidance": "Deploy automated malware analysis, YARA AST scanners, and verify heuristic detection engines are active.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_malware_prevention",
    },
    {
        "id": "SOC2-CC7.1",
        "framework_id": "SOC2",
        "control_code": "CC7.1",
        "title": "Vulnerability Management & Patch Governance",
        "domain": "System Operations",
        "description": "The entity uses vulnerability detection tools and methodologies to identify, report, and remediate technical vulnerabilities.",
        "remediation_guidance": "Resolve all unpatched Critical and High severity vulnerabilities (CVSS >= 7.0) across all managed assets.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_vulnerability_hygiene",
    },
    {
        "id": "SOC2-CC7.2",
        "framework_id": "SOC2",
        "control_code": "CC7.2",
        "title": "Infrastructure Anomaly Monitoring & Alerting",
        "domain": "System Operations",
        "description": "The entity monitors system components and the operation of controls for anomalies and potential security incidents.",
        "remediation_guidance": "Maintain continuous SIEM log ingestion, active correlation rules, and zero unsuppressed critical alert backlogs.",
        "severity": ControlSeverity.HIGH,
        "evaluator_key": "eval_anomaly_monitoring",
    },
    {
        "id": "SOC2-CC7.3",
        "framework_id": "SOC2",
        "control_code": "CC7.3",
        "title": "Incident Response & Forensic Readout",
        "domain": "System Operations",
        "description": "The entity evaluates and responds to identified security incidents according to defined incident response protocols.",
        "remediation_guidance": "Contain or resolve all open Critical security incidents and maintain immutable evidence locker seals.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_incident_containment",
    },

    # --- ISO/IEC 27001:2022 ---
    {
        "id": "ISO27001-A.5.15",
        "framework_id": "ISO27001",
        "control_code": "A.5.15",
        "title": "Access Control Management",
        "domain": "Organizational Controls",
        "description": "Rules to control physical and logical access to information and other associated assets shall be established and maintained.",
        "remediation_guidance": "Audit role-based permissions matrix to ensure principle of least privilege across all user tiers.",
        "severity": ControlSeverity.HIGH,
        "evaluator_key": "eval_access_controls",
    },
    {
        "id": "ISO27001-A.8.7",
        "framework_id": "ISO27001",
        "control_code": "A.8.7",
        "title": "Protection Against Malware",
        "domain": "Technological Controls",
        "description": "Protection against malware shall be implemented and supported by appropriate user awareness.",
        "remediation_guidance": "Ensure Bloom filter IoC database and safe binary static analyzers are active and loaded with latest threat signatures.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_malware_prevention",
    },
    {
        "id": "ISO27001-A.8.8",
        "framework_id": "ISO27001",
        "control_code": "A.8.8",
        "title": "Management of Technical Vulnerabilities",
        "domain": "Technological Controls",
        "description": "Information about technical vulnerabilities of information systems being used shall be obtained and evaluated.",
        "remediation_guidance": "Scan all discovered endpoints and resolve critical CVE exposures within standard SLA windows.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_vulnerability_hygiene",
    },
    {
        "id": "ISO27001-A.8.15",
        "framework_id": "ISO27001",
        "control_code": "A.8.15",
        "title": "Logging and Tamper Evidence",
        "domain": "Technological Controls",
        "description": "Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, and protected against tampering.",
        "remediation_guidance": "Maintain immutable WORM audit ledger with SHA-256 hash chains and verified HMAC signatures.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_audit_tamper_resistance",
    },
    {
        "id": "ISO27001-A.8.16",
        "framework_id": "ISO27001",
        "control_code": "A.8.16",
        "title": "Monitoring Activities & Threat Detection",
        "domain": "Technological Controls",
        "description": "Networks, systems and applications shall be monitored for abnormal behavior and appropriate actions taken.",
        "remediation_guidance": "Ensure UEBA behavioral baselining and Sigma/YARA AST rules engines are operating with zero ingestion backlog.",
        "severity": ControlSeverity.HIGH,
        "evaluator_key": "eval_anomaly_monitoring",
    },
    {
        "id": "ISO27001-A.8.20",
        "framework_id": "ISO27001",
        "control_code": "A.8.20",
        "title": "Network Security & Segmentation",
        "domain": "Technological Controls",
        "description": "Networks and network devices shall be secured, managed and controlled to protect information in systems.",
        "remediation_guidance": "Enforce strict IP subnet boundary isolation and isolate identified rogue or compromised assets.",
        "severity": ControlSeverity.HIGH,
        "evaluator_key": "eval_network_segmentation",
    },

    # --- NIST CSF 2.0 ---
    {
        "id": "NIST-ID.AM-01",
        "framework_id": "NIST_CSF",
        "control_code": "ID.AM-01",
        "title": "Inventories of Hardware & Devices",
        "domain": "Identify (Asset Management)",
        "description": "Inventories of hardware managed by the organization are maintained and cataloged.",
        "remediation_guidance": "Perform continuous ARP and subnet scanning to maintain zero unmanaged/rogue devices.",
        "severity": ControlSeverity.HIGH,
        "evaluator_key": "eval_asset_inventory",
    },
    {
        "id": "NIST-PR.AC-01",
        "framework_id": "NIST_CSF",
        "control_code": "PR.AC-01",
        "title": "Identities and Credentials Management",
        "domain": "Protect (Access Control)",
        "description": "Identities and credentials for authorized users, services, and hardware are managed throughout their lifecycle.",
        "remediation_guidance": "Audit administrative user accounts and ensure session timeouts and RBAC controls are enforced.",
        "severity": ControlSeverity.HIGH,
        "evaluator_key": "eval_access_controls",
    },
    {
        "id": "NIST-PR.PS-02",
        "framework_id": "NIST_CSF",
        "control_code": "PR.PS-02",
        "title": "Software Vulnerabilities Management",
        "domain": "Protect (Platform Security)",
        "description": "Software is maintained, replaced, or remediated to prevent exploitation of known vulnerabilities.",
        "remediation_guidance": "Remediate vulnerabilities with CVSS scores above 7.0 and ensure automated vulnerability scans run weekly.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_vulnerability_hygiene",
    },
    {
        "id": "NIST-DE.CM-01",
        "framework_id": "NIST_CSF",
        "control_code": "DE.CM-01",
        "title": "Network and Environmental Monitoring",
        "domain": "Detect (Continuous Monitoring)",
        "description": "Networks and environments are monitored to detect potential cybersecurity events and unauthorized behavior.",
        "remediation_guidance": "Verify SIEM log streams, ML anomaly inference pipelines, and CS-QL detection rules are operational.",
        "severity": ControlSeverity.HIGH,
        "evaluator_key": "eval_anomaly_monitoring",
    },
    {
        "id": "NIST-RS.RP-01",
        "framework_id": "NIST_CSF",
        "control_code": "RS.RP-01",
        "title": "Incident Response Plan Execution",
        "domain": "Respond (Response Planning)",
        "description": "The incident response plan is executed during or after an incident.",
        "remediation_guidance": "Execute automated SOAR playbooks for critical threats and maintain formal incident timelines.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_incident_containment",
    },

    # --- PCI-DSS v4.0 ---
    {
        "id": "PCI-1.2.1",
        "framework_id": "PCI_DSS",
        "control_code": "1.2.1",
        "title": "Network Traffic Restriction",
        "domain": "Network Security Controls",
        "description": "Inbound and outbound traffic to and from the cardholder data environment is restricted to that which is necessary.",
        "remediation_guidance": "Ensure network zone isolation and zero unauthorized bridges between untrusted and secure zones.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_network_segmentation",
    },
    {
        "id": "PCI-5.2.1",
        "framework_id": "PCI_DSS",
        "control_code": "5.2.1",
        "title": "Anti-Malware & Threat Detection",
        "domain": "Malicious Software Protection",
        "description": "An anti-malware solution is deployed on all system components commonly affected by malicious software.",
        "remediation_guidance": "Maintain active malware static hashing, CTPH fuzzy clustering, and signature scanning on all endpoints.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_malware_prevention",
    },
    {
        "id": "PCI-6.3.3",
        "framework_id": "PCI_DSS",
        "control_code": "6.3.3",
        "title": "Vulnerability Remediation SLAs",
        "domain": "Secure Software & Vulnerabilities",
        "description": "All critical software vulnerabilities are patched within one month of release.",
        "remediation_guidance": "Patch all high and critical CVEs across cardholder environment systems within the 30-day window.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_vulnerability_hygiene",
    },
    {
        "id": "PCI-10.2.1",
        "framework_id": "PCI_DSS",
        "control_code": "10.2.1",
        "title": "Audit Logs for System Access & Events",
        "domain": "Log Monitoring & Testing",
        "description": "Audit logs are enabled and active for all system components, recording all individual access to cardholder data.",
        "remediation_guidance": "Ensure all user sessions, administrative changes, and containment events are cryptographically sealed in the vault.",
        "severity": ControlSeverity.HIGH,
        "evaluator_key": "eval_audit_tamper_resistance",
    },

    # --- HIPAA Security Rule ---
    {
        "id": "HIPAA-164.312a",
        "framework_id": "HIPAA",
        "control_code": "164.312(a)",
        "title": "Access Control (Technical Safeguards)",
        "domain": "Technical Safeguards",
        "description": "Implement technical policies and procedures for electronic information systems that maintain ePHI to allow access only to authorized persons.",
        "remediation_guidance": "Enforce individual user credentials, automatic logoff, and strict RBAC permission verification.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_access_controls",
    },
    {
        "id": "HIPAA-164.312b",
        "framework_id": "HIPAA",
        "control_code": "164.312(b)",
        "title": "Audit Controls & Record Review",
        "domain": "Technical Safeguards",
        "description": "Implement hardware, software, and procedural mechanisms that record and examine activity in information systems containing ePHI.",
        "remediation_guidance": "Maintain immutable WORM audit logs with continuous hash-chain integrity verification.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_audit_tamper_resistance",
    },
    {
        "id": "HIPAA-164.312c",
        "framework_id": "HIPAA",
        "control_code": "164.312(c)",
        "title": "Integrity of Electronic Protected Health Information",
        "domain": "Technical Safeguards",
        "description": "Implement policies and procedures to protect ePHI from improper alteration or destruction.",
        "remediation_guidance": "Verify cryptographic hashes and HMAC seals on all stored security records and evidence lockers.",
        "severity": ControlSeverity.HIGH,
        "evaluator_key": "eval_audit_tamper_resistance",
    },

    # --- GDPR ---
    {
        "id": "GDPR-Art25",
        "framework_id": "GDPR",
        "control_code": "Art. 25",
        "title": "Data Protection by Design & Default",
        "domain": "Data Governance",
        "description": "Implement appropriate technical and organizational measures designed to implement data protection principles in an effective manner.",
        "remediation_guidance": "Scrub sensitive fields (passwords, tokens) across all telemetry pipelines and enforce least privilege.",
        "severity": ControlSeverity.HIGH,
        "evaluator_key": "eval_access_controls",
    },
    {
        "id": "GDPR-Art32",
        "framework_id": "GDPR",
        "control_code": "Art. 32",
        "title": "Security of Processing",
        "domain": "Security Measures",
        "description": "Implement appropriate technical and organizational measures to ensure a level of security appropriate to the risk.",
        "remediation_guidance": "Maintain active vulnerability scanning, malware defense, and anomaly detection engines.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_vulnerability_hygiene",
    },
    {
        "id": "GDPR-Art33",
        "framework_id": "GDPR",
        "control_code": "Art. 33",
        "title": "Incident Notification Readiness",
        "domain": "Breach Management",
        "description": "In the case of a personal data breach, notify the supervisory authority without undue delay and within 72 hours.",
        "remediation_guidance": "Maintain automated incident escalation workflows and immediate containment capabilities via SOAR.",
        "severity": ControlSeverity.CRITICAL,
        "evaluator_key": "eval_incident_containment",
    },
]
