"""CyberShield Enterprise - Autonomous LLM Guardrail & Prompt Injection Sentinel Schemas.
Data contracts for prompt injection inspection, jailbreak defense, system prompt leak prevention,
and harmful exploit synthesis mitigation.
"""

from enum import Enum
from typing import Dict, List, Optional, Any
from datetime import datetime, timezone
from pydantic import BaseModel, Field


class LLMThreatCategory(str, Enum):
    DIRECT_PROMPT_INJECTION = "DIRECT_PROMPT_INJECTION"
    INDIRECT_PROMPT_INJECTION = "INDIRECT_PROMPT_INJECTION"
    JAILBREAK_ROLEPLAY_OVERRIDE = "JAILBREAK_ROLEPLAY_OVERRIDE"
    SYSTEM_PROMPT_EXTRACTION = "SYSTEM_PROMPT_EXTRACTION"
    CANARY_TOKEN_LEAK = "CANARY_TOKEN_LEAK"
    WEAPONIZED_EXPLOIT_OUTPUT = "WEAPONIZED_EXPLOIT_OUTPUT"
    UNICODE_HOMOGLYPH_EVASION = "UNICODE_HOMOGLYPH_EVASION"


class GuardrailAction(str, Enum):
    BLOCK_REQUEST = "BLOCK_REQUEST"
    REDACT_PROMPT = "REDACT_PROMPT"
    AUDIT_ONLY = "AUDIT_ONLY"


class PromptInspectionRequest(BaseModel):
    """User prompt or document chunk to inspect before passing to LLM."""
    prompt_text: str = Field(..., description="User input, system message, or retrieved RAG context")
    user_id: Optional[str] = "unknown_user"
    application_name: str = "Enterprise-Assistant"
    allow_redaction: bool = False


class CompletionInspectionRequest(BaseModel):
    """LLM generated output to inspect before returning to user."""
    completion_text: str = Field(..., description="Raw output generated by the LLM")
    system_prompt_canary: Optional[str] = Field(default=None, description="Secret canary token embedded in system prompt")
    application_name: str = "Enterprise-Assistant"


class LLMGuardrailAlert(BaseModel):
    """Security alert raised on prompt injection or adversarial LLM abuse."""
    alert_id: str
    category: LLMThreatCategory
    severity: str = "HIGH"
    mitre_atlas_technique: str
    action_enforced: GuardrailAction
    raw_trigger_snippet: str
    details: str
    countermeasure: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class PromptInspectionResponse(BaseModel):
    """Result of prompt guardrail analysis."""
    is_safe: bool
    detected_threat: Optional[LLMThreatCategory] = None
    action_taken: GuardrailAction
    sanitized_prompt: str
    alert: Optional[LLMGuardrailAlert] = None
    latency_ms: float


class CompletionInspectionResponse(BaseModel):
    """Result of completion guardrail analysis."""
    is_safe: bool
    detected_threat: Optional[LLMThreatCategory] = None
    canary_leaked: bool = False
    alert: Optional[LLMGuardrailAlert] = None
    sanitized_completion: str


class LLMGuardrailMetrics(BaseModel):
    """Platform-wide LLM firewall performance and threat counters."""
    total_prompts_scanned: int
    total_injections_blocked: int
    jailbreak_attempts_stopped: int
    canary_leaks_prevented: int
    active_firewall_status: str = "ACTIVE_DEFENSE_OPTIMAL"
